{{ if ne .Environment "e2e" }}
apiVersion: "zalando.org/v1"
kind: PlatformCredentialsSet
metadata:
  name: api-monitoring-controller-credentials
  namespace: kube-system
spec:
  application: api-monitoring-controller
  tokens:
    container-api-scanner:
      privileges: []
{{ end }}
